name: Atualizar_Aerodromos_ANAC

on:
  schedule:
    - cron: '0 3 1 * *'  # Executa às 03:00 UTC todo dia 1º do mês
  workflow_dispatch:     # Permite execução manual também

jobs:
  atualizar-json:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Baixar JSON da ANAC
        run: curl -L -o AerodromosPublicos.json "https://sistemas.anac.gov.br/dadosabertos/Aerodromos/Aer%C3%B3dromos%20P%C3%BAblicos/Lista%20de%20aer%C3%B3dromos%20p%C3%BAblicos/AerodromosPublicos.json"

      - name: Commit e push se houver mudanças
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add AerodromosPublicos.json
          if git diff --cached --quiet; then
            echo "Nenhuma atualização encontrada."
          else
            git commit -m "Atualização mensal do AerodromosPublicos.json via GitHub Actions"
            git push
          fi
